clearInventoryStart: false
clearInventoryEnd: true
moveDuringCountdown: false
countdownDuration: 5
lootSpawn: false
lootSpawnNearPlayers: true
lootChance: 50
lootSpawnRadius: 10
autoLoad: false
autoLoadTask: default
allowPlayerReady: true
enableReward: true
lootWorld: world
forcePlayersOnTeam: true
allowCompassTracking: true
