package stretch.lockout.game;

public enum GameRule {
    ANIMATED_SCOREBOARD, CLEAR_INV_START, CLEAN_INV_END, COUNTDOWN_MOVE, SPAWN_LOOT, LOOT_NEAR, AUTO_LOAD, ALLOW_REWARD,
    FORCE_TEAM, COMPASS_TRACKING, MAX_SCORE
}
